name: Build and Deploy

env:
  ENVIRONMENT: staging

on:
  push:
    branches:
      - master

jobs:
  code-quality:
    name: Code quality
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Install golint
        run: go install golang.org/x/lint/golint@latest

      - name: Go-lint
        run: golint ./...

      - name: Run go vet
        run: go vet ./...

      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Run staticcheck
        run: staticcheck ./...

      - name: Check fmt
        run: ./scripts/check_fmt.sh

      - name: Unit tests
        run: go test $(go list ./... | grep -v '/integrationtest') -v